# Generated by Django 2.2.2 on 2019-07-19 15:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('harvest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HarvestSubmission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.TextField(help_text='The name of the event submitted to Harvest', verbose_name='event name')),
                ('task_id', models.IntegerField(help_text='Task id the event is associated with on Harvest', verbose_name='task id')),
                ('project_id', models.IntegerField(help_text='Project id the event is associated with on Harvest', verbose_name='project id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
