# Generated by Django 2.2.2 on 2019-07-19 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('harvest', '0002_harvestsubmission'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='harvestsubmission',
            name='task_id',
        ),
        migrations.AddField(
            model_name='harvestsubmission',
            name='assignment_id',
            field=models.IntegerField(help_text='Assignment id the event is associated with on Harvest', null=True, verbose_name='assignment id'),
        ),
        migrations.AlterField(
            model_name='harvestsubmission',
            name='project_id',
            field=models.IntegerField(help_text='Project id the event is associated with on Harvest', null=True, verbose_name='project id'),
        ),
    ]
